// Generated by scripts/build-content.mjs from cv_data.json, with meta.email
// and meta.phone removed. Never import cv_data.json directly from anything the
// browser can download — the bundler inlines the whole module, stripped fields
// and all. See scripts/build-content.mjs for the full explanation.
import cvPublic from './cv.public.json';
import projectsJson from './projects.json';

export type Cv = typeof cvPublic;
export type Meta = Cv['meta'];

export const cv: Cv = cvPublic;
export const projects = projectsJson;

/** Categories rendered in the skills table, in order. `lead` gets the accent. */
export const SKILL_ORDER: { key: keyof Cv['skills']; label: string; lead?: boolean }[] = [
  { key: 'AI / LLM', label: 'AI & agents', lead: true },
  { key: 'Languages', label: 'Languages' },
  { key: 'Backend', label: 'Backend' },
  { key: 'Frontend', label: 'Frontend' },
  { key: 'Databases', label: 'Data' },
  { key: 'Cloud & DevOps', label: 'Cloud & DevOps' },
  { key: 'Practices', label: 'Architecture & practice' },
];

/** Roles shown before the "show earlier roles" disclosure. */
export const VISIBLE_ROLES = 5;

export const LINKS = {
  linkedin: cv.meta.linkedin,
  github: cv.meta.github,
  scholar: cv.meta.scholar_url,
  toptal: 'https://www.toptal.com/developers/resume/abdelhamid-awad-abdelhamid-attaby#NV1dgj',
};

export const SITE = {
  url: 'https://abdelhamid-attaby.github.io',
  title: 'Abdelhamid Attaby — Senior Software Engineer, Ph.D.',
  description:
    'Senior software engineer with 15+ years building large-scale systems, including two years at GitHub (Microsoft). Twice CTO. Now building production multi-agent AI systems. Ask my CV anything.',
};
